### ISSUE TITLE
Private Bitbucket repos support?

### ISSUE THREAD

**Issue by dwiyatci** [neoascetic/rawgithack#11]
Hi! I have [some private repository in BitBucket](https://bitbucket.org/dwiyatci/hello-private), and I tried to `rawgithack` these following URLs of my repo:

- https://bitbucket.org/dwiyatci/hello-private/raw/master/index.html
- https://bitbucket.org/dwiyatci/hello-private/raw/50c67ea88982b12d5a2ea3ba97b439f3a89ec288/index.html

...and it didn't work. Is githack currently not supporting private repos in BitBucket? If not, will there be any plan to support it in the future?

**Comment by neoascetic** [comment]
There is [no support](https://bitbucket.org/site/master/issues/8784/public-url-on-private-repositories-bb-9955) from Bitbucket at this moment for raw links to private repos, so I have no idea how to make it possible.

**Comment by dwiyatci** [comment]
Oh, thanks for pointing out to Bitbucket's official thread for the issue; at least I can still see some "life" there. So, shall we keep this open until further development? ;)

**Comment by neoascetic** [comment]
Let's close it for now. Bitbucket had this feature before, so, if they implemented it in the same way (using `token` GET parameter), then we don't need to do anything on our side (see #5).
