### ISSUE TITLE
Support Bitbucket snippets

### ISSUE THREAD

**Issue by jhult** [neoascetic/rawgithack#12]
It would be nice to support Bitbucket snippets.
- [Example 1 snippet URL](https://bitbucket.org/!api/2.0/snippets/mythics/yjyRr/9825d5a7570615d03d71b91b11926978035487c3/files/code.js)
- [Example 2 snippet URL](https://api.bitbucket.org/2.0/snippets/mythics/yjyRr/9825d5a7570615d03d71b91b11926978035487c3/files/code.js)

**Comment by neoascetic** [comment]
Yeah, feel free to make a PR

**Comment by ddhhz** [comment]
Example 1 already works
https://bb.githack.com/!api/2.0/snippets/mythics/yjyRr/9825d5a7570615d03d71b91b11926978035487c3/files/code.js
and
https://bbcdn.githack.com/!api/2.0/snippets/mythics/yjyRr/9825d5a7570615d03d71b91b11926978035487c3/files/code.js

Just not in the gui.

**Comment by jhult** [comment]
@ddhhz, thanks! That works great.

You can even replace the commit ID with 'master'.

https://bb.githack.com/!api/2.0/snippets/mythics/yjyRr/master/files/jira_log_quick_work.js

https://bbcdn.githack.com/!api/2.0/snippets/mythics/yjyRr/master/files/jira_log_quick_work.js

**Comment by neoascetic** [comment]
![](http://www.reactiongifs.com/r/mgc.gif)

Need to add it to the GUI, though

**Comment by dlenski** [comment]
> It would be nice to support Bitbucket snippets.
>
> Example 1 snippet URL
> Example 2 snippet URL

Nice! I've been looking for something like this for a while.

The JSON sent by the API (e.g. https://bitbucket.org/!api/2.0/snippets/dlenski/6eEX6q) shows how to map from the human-friendly URL (blue link below) to the API URL, which is what's actually required to access the bare file:

![screenshot from 2017-12-21 17-11-46](https://user-images.githubusercontent.com/128716/34281232-16e19332-e672-11e7-9bfb-9c841acb32cb.png)

```json
{
  "scm": "git",
  "files": {
    "test.md": {
      "links": {
        "self": {
          "href": "https://bitbucket.org/!api/2.0/snippets/dlenski/6eEX6q/887f4841ebd3f2e108ce12ea7b5569f3fec3fcfa/files/test.md"
        },
        "html": {
          "href": "https://bitbucket.org/snippets/dlenski/6eEX6q/revisions/887f4841ebd3f2e108ce12ea7b5569f3fec3fcfa#file-test.md"
        }
      }
    }
  },
```

In three steps:

1) Human URL from the web interface looks like `https://bitbucket.org/snippets/dlenski/6eEX6q#file-test.md`
  * Or for a specific revision it looks like `https://bitbucket.org/snippets/dlenski/6eEX6q/revisions/887f4841ebd3f2e108ce12ea7b5569f3fec3fcfa#file-test.md`
  * If the filename has unusual characters, they'll be URL-escaped in the human URL: `https://bitbucket.org/snippets/dlenski/zeEX4b#file-test%20file%20%2522with%20a%20WEIRD%21%20name%2522.json` and in the API URL `https://bitbucket.org/!api/2.0/snippets/dlenski/zeEX4b/HEAD/files/test%20file%20%2522with%20a%20WEIRD!%20name%2522.json`
2) API URL looks like `https://bitbucket.org/!api/2.0/snippets/dlenski/6eEX6q/HEAD/files/test.md`
3) Rawgit URL looks like: https://bb.githack.com/!api/2.0/snippets/dlenski/6eEX6q/HEAD/files/test.md`

I think it should be pretty straightforward to allow rawgithack to recognize the API URLs… but handling the "human" URLs will require parsing the [URI fragment](https://en.wikipedia.org/wiki/Fragment_identifier) and moving it into the URI path.
