### ISSUE TITLE
Reduce Caching To 2 Hours

### ISSUE THREAD

**Issue by indolering** [neoascetic/rawgithack#14]
The website states that results are cached for "1 year" which is excessive.  Cache hits follow a zipf distribution, the general rule-of-thumb for TTL : cache hit rate is (very roughly) 15 minutes : 85%, 1 hour : 95% and 24 hours : 97%.  The Cloudflare cache also respects ETags, so you shouldn't need to do a lot of processing.

You have a unique set of customers so YMMV, but it couldn't hurt to experiment.  I would drop the browser-side cache to 15 minutes or an hour and just report Cloudflare's standard 2-hour cache.

**Comment by neoascetic** [comment]
See [this comment](https://github.com/neoascetic/rawgithack/issues/15#issuecomment-247017002).

**Comment by indolering** [comment]
I get that you can use hash tags in the URL, but 1 year is insane.  Reducing it to 24 hours will work too.

**Comment by neoascetic** [comment]
[Google recommends](
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching) 1
year as preferable cache time

**Comment by neoascetic** [comment]
[Google recommends](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching) 1
year as preferable cache time

**Comment by indolering** [comment]
Of course they do, they are obsessed with performance.  You can also cache DNS records for a year, but of the top 1 million websites only a handful cache for longer than a day and very few (mainly Facebook and Google) cache for longer than a week.

Githack's primary use case is for serving random stuff from their git repo directly.  A year long load time makes a minor mistake much worse, [this is not a hypothetical scenario](https://github.com/rgrove/rawgit/issues/111).  People looking to shave a single ETag check on 5% of page loads should throw their assets on a real CDN.
