### ISSUE TITLE
Gitlab support is broken?

### ISSUE THREAD

**Issue by ping** [neoascetic/rawgithack#18]
Is the support for Gitlab complete?

I pasted this random link (as an example) https://gitlab.com/dankremniov/holiday-confession/blob/900c112f5673b247830ec88d829011cfa4a5da62/build/images/backgrounds/1.jpg and the site generates the CDN hosted version as https://glcdn.githack.com/dankremniov/holiday-confession/raw/900c112f5673b247830ec88d829011cfa4a5da62/build/images/backgrounds/1.jpg.

However, that link simply redirects back to gitlab as seen below.

```
$ curl -I "https://glcdn.githack.com/dankremniov/holiday-confession/raw/900c112f5673b247830ec88d829011cfa4a5da62/build/images/backgrounds/1.jpg"
HTTP/1.1 301 Moved Permanently
Date: Tue, 08 Nov 2016 08:59:12 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Set-Cookie: __cfduid=df5855d81064f688ac6fd7077fd2177b01478595552; expires=Wed, 08-Nov-17 08:59:12 GMT; path=/; domain=.githack.com; HttpOnly
Location: https://gitlab.com/dankremniov/holiday-confession/raw/900c112f5673b247830ec88d829011cfa4a5da62/build/images/backgrounds/1.jpg
CF-Cache-Status: MISS
Expires: Wed, 08 Nov 2017 08:59:12 GMT
Cache-Control: public, max-age=31536000
Server: cloudflare-nginx
CF-RAY: 2fe7d3dbbeca31b0-SIN
```

**Comment by ping** [comment]
Realised this is due to jpg not being a supported type. Fixed in #19.

**Comment by neoascetic** [comment]
Gitlab serves correct media type for the given link, so there is nothing wrong with the redirect.

**Comment by neoascetic** [comment]
I think for CDN URLs there must be no redirect (this address #20 as well). So, let's keep this open for now.

**Comment by neoascetic** [comment]
It has been fixed! Thank you, @ping, for the report. You can try it out (make sure your browser's cache is invalidated).
