### ISSUE TITLE
Forwarding to Gitlab

### ISSUE THREAD

**Issue by shoemakerlevy9** [neoascetic/rawgithack#21]
Hi,

I'm setting rawgithack up for a html page stored on Gitlab, but the url  I get from rawgithack.com forwards me to the gitlab sign in page instead of serving the html. My repo is private. Does that ruin things?
https://gl.githack.com/digilabs/GooseChaserRover/raw/Pre-Release_V0.2/wiki/wikipage.html

**Comment by neoascetic** [comment]
Due to security circumstances, private repos are not supported
