### ISSUE TITLE
hostslt list do not work

### ISSUE THREAD

**Issue by KonoromiHimaries** [neoascetic/rawgithack#27]
![2018-10-21-window](https://user-images.githubusercontent.com/5884000/47266621-6fc78900-d539-11e8-8df3-1d77b80bb9f8.png)

test link <code>https://raw.githubusercontent.com/lewisje/jansal/master/adblock/hostslt</code>

**Comment by neoascetic** [comment]
That’s simply because the URL doesn’t have file extension and thus the correct mime type cannot be detected. You could use GitHub directly for simple text files, don’t you?

**Comment by KonoromiHimaries** [comment]
![2018-10-21-gitcdn - a powerful cdn for github files](https://user-images.githubusercontent.com/5884000/47269248-63ecbe80-d55b-11e8-9f94-c6f30841a5b5.png)
example. <code>https://gitcdn.xyz/repo/lewisje/jansal/master/adblock/hostslt</code>

**Comment by neoascetic** [comment]
OK, I see. I’ll try to do something.
