### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by anishkny** [neoascetic/rawgithack#31]
Hey this is an awesome repo! especially now that rawgit.com is [going away](https://rawgit.com).

I was trying to run this repo locally:

```
docker build -t rawgithack .
docker run -p 8080:80 rawgithack &
[1] 70585
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
7742acb7107c        rawgithack          "nginx -g 'daemon of…"   3 seconds ago       Up 2 seconds        0.0.0.0:8080->80/tcp   gracious_lovelace
```

Then I see this at localhost:8080:

<img width="764" alt="screen shot 2018-10-26 at 2 19 28 pm" src="https://user-images.githubusercontent.com/357499/47585031-32447080-d92a-11e8-9274-153b830ef4db.png">

But how do test it out locally?

Thanks!

**Comment by neoascetic** [comment]
Well, the service itself need to be changed a bit to allow seamless local development (i. e. support of custom domains). Currently I am simply adding raw.githack.com as an alias of `127.0.0.1` in `/etc/hosts`.

**Comment by anishkny** [comment]
Ok. I am complete `nginx` noob. I tried adding this to `/etc/hosts` inside the container:

```
# cat hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	f52093c62453

127.0.0.1 raw.githack.com.     # <---- added
```

but not sure how that helps run locally.

**Comment by neoascetic** [comment]
No, you need to add those lines locally, on your host machine

**Comment by neoascetic** [comment]
I assume everything is fine right now

**Comment by neoascetic** [comment]
However, I’d rather leave it open until the correct way to run the project locally will be implemented

**Comment by anishkny** [comment]
Yeah I actually didn't get a chance to try it out. It would be cool to see a noob-friendly way to run this locally. :v:

**Comment by neoascetic** [comment]
[The proposed solution](https://github.com/neoascetic/rawgithack/issues/31#issuecomment-433595734) is the way to go, I actually do use it in development.
