### ISSUE TITLE
raw.githack.com Favicon

### ISSUE THREAD

**Issue by neooblaster** [neoascetic/rawgithack#32]
Hi neoascetic,

Do you think it's possible to add a Favicon ?
I made little hack to reuse rawgit.com Favicon to identify you webapp ;) 

If use full path to get the image :

``<link rel="icon" href="/path/to/favicon.png">``

![image](https://user-images.githubusercontent.com/22078558/47963358-7242dc00-e02b-11e8-9527-747998aae9a5.png)

![sushi](https://user-images.githubusercontent.com/22078558/47963360-78d15380-e02b-11e8-86c0-6d376bf7e856.png)

Maybe you want to add your own custom Icon ;)

I take advantage to thank you for your githack.com service.

Best regards,
Nicolas D.

**Comment by neoascetic** [comment]
Hello. Thank you for request. Check the new icon out :)

**Comment by neooblaster** [comment]
Hi Neoascetic !

Thank you for your reply and the implementation of the Favicon.
I confirm that works perfectly, my bookmark icon has been updated automatically ;)

![image](https://user-images.githubusercontent.com/22078558/48377534-619b0180-e6ce-11e8-9dae-e710a8422ca5.png)

Best Regards,
Neoblaster
