### ISSUE TITLE
A way to invalidate the cache?

### ISSUE THREAD

**Issue by matthewmcneely** [neoascetic/rawgithack#33]
First off, thanks for running this... 

I'd like to be able to offer 'latest'-tag functionality for accessing a gitlab-hosted JS file. I'm updating my 'latest' tag whenever I update this file. But of course, your CDN will cache that record for a year. Is there a way to send a parameter to CDN that invalidates the rawcdn entry with the new file?

**Comment by matthewmcneely** [comment]
I see that in commit https://github.com/neoascetic/rawgithack/commit/8f2f9352a4ab96c5fbf304c45c2b88f822e5600c that master branches have a 5 min TTL; I can use that mechanism. You might consider adding a test for the 'latest' tag to support the same construct.

**Comment by neoascetic** [comment]
Well, I can, but there are infinite number of names for the branches people consider «the latest». Usually it is a master branch.

**Comment by matthewmcneely** [comment]
Fair point. But I do see */latest/* in both JS and Docker versioning, so definitely not *arbitrary*. But I understand the reluctance: where does it end, right?

**Comment by neoascetic** [comment]
Right

**Comment by neoascetic** [comment]
Hello everyone interested in cache invalidation!

I’ve implemented the beta version of cache invalidation functionality - there is the form on the main page. Currently, you can only invalidate CDN URLs (which is obvious - we should not have problems with the regular ones). Please check it out and let me know what do you think.

Thanks!
