### ISSUE TITLE
GitLab Subgroups

### ISSUE THREAD

**Issue by nerothe** [neoascetic/rawgithack#34]
Gitlab Repositorys and Groups can be in Groups
_https://gitlab.com/nerothe/js/holiday.js/blob/v1.0.0/holiday.js_
Where "nerothe" is user and "js" is a subgroup then "holiday.js" is a project
Also a link like:
_https://gitlab.com/user/group/subgroup/subsubgroup/.../project/blob/TAG/FILE_
could happen.
This seems to be not supported by rawgithack.

**Comment by neoascetic** [comment]
Ooops, looks like this have to be fixed :)
Thanks for the report!
