### ISSUE TITLE
Gitlab query parameters not passed on

### ISSUE THREAD

**Issue by kasbah** [neoascetic/rawgithack#39]
Hey, neat service! 

I was trying to use the following with CORS through rawgithack. https://gitlab.com/openflexure/openflexure-microscope/-/jobs/artifacts/master/raw/builds/main_body_LS65.stl?job=STLs
The form on your site says it will be `https://gl.githack.com/openflexure/openflexure-microscope/-/jobs/artifacts/master/raw/builds/main_body_LS65.stl` but it's missing the `?job=STLs`.

**Comment by neoascetic** [comment]
This is intended. Things are cached with ignore of query string, so you’ll get the same result if you do not pass any query string.

**Comment by kasbah** [comment]
Hmm, but https://gl.githack.com/openflexure/openflexure-microscope/-/jobs/artifacts/master/raw/builds/main_body_LS65.stl serves a 404 and https://gl.githack.com/openflexure/openflexure-microscope/-/jobs/artifacts/master/raw/builds/main_body_LS65.stl?job=STLs serves the file :/

**Comment by neoascetic** [comment]
Hmmm, I will take a look at this

**Comment by neoascetic** [comment]
Well, this is so because the URLs you've provided point to CI/CD jobs and not to a source code behind the project. CI/CD jobs are currently not supported.

**Comment by neoascetic** [comment]
URLs from issue #40 work because they point to a specific job by its id

**Comment by neoascetic** [comment]
Since gitlab's CI/CD URLs are not supported at this moment, I consider this closed. You should use specific build URL (which are working as an undocumented feature). Feel free to create a request to support CI/CD, but I've created #41 which should help with this issue once implemented.
