### ISSUE TITLE
Re-direct results in not being able to bypass CORS

### ISSUE THREAD

**Issue by kasbah** [neoascetic/rawgithack#40]
I am not sure bypassing gitlabs CORS policy on artifacts is one of the goals of this project but I would find that really handy. It currently works for most artifacts but not when you are trying to use re-directs. 

https://glcdn.githack.com/openflexure/openflexure-microscope/-/jobs/artifacts/master/raw/builds/main_body_LS65.stl?job=STLs 

re-directs to 

https://gitlab.com/openflexure/openflexure-microscope/-/jobs/223115318/artifacts/raw/builds/main_body_LS65.stl

so when I try and use URLs like that that grab the latest artifacts from the master branch I get CORS errors.

**Comment by kasbah** [comment]
Relevant: https://stackoverflow.com/questions/20254456/intercepting-backend-301-302-redirects-proxy-pass-and-rewriting-to-another-loc

**Comment by neoascetic** [comment]
Hello. That’s because .stl is not supported extension. When we do not support something, we simply redirect to the origin. That’a why you have CORS problems.

Do you want .stl to be supported?

**Comment by kasbah** [comment]
That would be great! MIME is `model/stl` I believe. https://www.iana.org/assignments/media-types/model/stl

**Comment by neoascetic** [comment]
STLs are now supported. But you have to use specific job URL if you want them to work.
