### ISSUE TITLE
Gitea support

### ISSUE THREAD

**Issue by pat-s** [neoascetic/rawgithack#45]
Would it be possible to add [Gitea](https://github.com/go-gitea/gitea) support?

Thanks for the cool project!

**Comment by neoascetic** [comment]
Isn't Gitea is self-hosted service?

**Comment by neoascetic** [comment]
Oh, right, here is the main page: https://gitea.com. I'll see what can I do.

**Comment by neoascetic** [comment]
Please feel free to open PR. Closing meanwhile.
