### ISSUE TITLE
HTTP proto

### ISSUE THREAD

**Issue by determin1st** [neoascetic/rawgithack#48]
Because of "[Mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)" limitations with the browser fetch API / xmlHttpRequest,
scripts that send requests to `http://` are not working.. So, should it be enabled?

**Comment by neoascetic** [comment]
What is your proposal for fixing this problem?

**Comment by determin1st** [comment]
Disable `http` to `https` url rewrite (probably)?

Here is the example URL:
https://raw.githack.com/determin1st/httpFetch/master/test-3/index.html

If you open devtools console F12, and press run button you will see errors about mixed content.

With this URL:
http://raw.githack.com/determin1st/httpFetch/master/test-3/index.html

No errors will appear.

**Comment by neoascetic** [comment]
Well, the service does not have any `http` -> `https` rewrites

**Comment by determin1st** [comment]
![1234](https://user-images.githubusercontent.com/16524081/67011640-72879a80-f109-11e9-98c4-8a827745a92f.jpg)

**Comment by neoascetic** [comment]
Oh, that’s because of HSTS. That’s why I didn’t see the redirect when trying to fetch the URL with curl. I will remove the `Strict-Transport-Security` header from the upstream. Thank you.

**Comment by neoascetic** [comment]
Could you please verify?

**Comment by determin1st** [comment]
I've dropped chrome cache at `chrome://net-internals/#hsts` and it's working fine now..
Both chrome and firefox are ok - Thanks!

![1234](https://user-images.githubusercontent.com/16524081/67042349-21939880-f141-11e9-8374-af50ec0850d1.jpg)
