### ISSUE TITLE
glcdn domain is down today

### ISSUE THREAD

**Issue by oxsilento** [neoascetic/rawgithack#52]
https://glcdn.githack.com is down.. is it happend fo everyone or just me?

**Comment by neoascetic** [comment]
It works for me, any particular URL?

**Comment by oxsilento** [comment]
https://glcdn.githack.com/xsilent-cleopatra/research-test/raw/master/imgfo/example-json-source-1.6.1.json

**Comment by neoascetic** [comment]
I am investigating this

**Comment by neoascetic** [comment]
It should be fixed now
