### ISSUE TITLE
Homepage at https://raw.githack.com/ results in 503

### ISSUE THREAD

**Issue by rajsite** [neoascetic/rawgithack#53]
The past couple of days making a request to the homepage results in a 503. For example, using a tool like postman to perform a GET request to https://raw.githack.com/

This breaks tools like awesome-lists that do link liveness validation. [Example validation failure](https://github.com/rajsite/awesome-webvis/runs/661466864?check_suite_focus=true#step:4:21).

**Comment by neoascetic** [comment]
The problem is that the service was under DDoS, so I've protected the root page with CloudFlare's JS Challenge protection. I've disabled it for now, let's see if that works.

**Comment by rajsite** [comment]
That worked for [awesome-lint](https://github.com/sindresorhus/awesome-lint) which is used by lists on [sindresorhus/awesome](https://github.com/sindresorhus/awesome)! [Example build](https://github.com/rajsite/awesome-webvis/runs/690073195).

Unfortunate that you were getting DDOS attacked. Hopefully there is a way to serve the homepage without loosing DDOS protection :/
