### ISSUE TITLE
Seems returning  wrong mime

### ISSUE THREAD

**Issue by metroroland** [neoascetic/rawgithack#56]
Hi, I have an image on github here:

https://rawcdn.githack.com/metroroland/blissful-eloquent-1xe3f/f1dda6c3144b2ff51d595ab5a712ebedcf763e83/src/assets/logo.png

From browse, the mime type of the resource is not an image.

Did I encounter a bug or something?

Thanks for developing the tool and devoting your time to help others.

Regards,

**Comment by neoascetic** [comment]
The problem is that the linked file is not actually a PNG image; the file itself is broken.
