### ISSUE TITLE
Question : multiple files

### ISSUE THREAD

**Issue by x4080** [neoascetic/rawgithack#58]
Is there anyway to quickly add multiple files to CDN ?

Thanks

**Comment by neoascetic** [comment]
Just request them through CDN URL, what’s the question?

**Comment by x4080** [comment]
Sorry to confuse you, in the website, we can only upload 1 file at a time is there a way to upload multiple files or folder at the same time?

**Comment by neoascetic** [comment]
You don’t upload anything on the website, the website just helps you build URLs (and you can build them manually). The files are being “uploaded” to the CDN when they first requested.

**Comment by x4080** [comment]
ok thanks
