### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by collinanderson** [neoascetic/rawgithack#6]
Just FYI. Pretty sure. :)

**Comment by neoascetic** [comment]
Yeah, something wrong with Digital Ocean :(
![screen shot 2015-02-07 at 09 34 52](https://cloud.githubusercontent.com/assets/725836/6091278/abea4fe2-aeac-11e4-9f3b-f08614bc1ae6.png)

**Comment by neoascetic** [comment]
It is up now! Anyway, thanks for the report!
