### ISSUE TITLE
Service seems offline

### ISSUE THREAD

**Issue by shyim** [neoascetic/rawgithack#60]
![image](https://user-images.githubusercontent.com/6224096/111035299-1918bd80-841a-11eb-919c-d138bc5d64f5.png)

**Comment by neoascetic** [comment]
Hello. Working on that.

**Comment by neoascetic** [comment]
Seems to be fixed. Sorry for inconvenience. There were problems with the network on the hosting side.

**Comment by shyim** [comment]
no problem. thanks for hosting it! 😊
