### ISSUE TITLE
Raw githack for GitLab is down today?

### ISSUE THREAD

**Issue by aalfiann** [neoascetic/rawgithack#61]
I just found that raw.githack.com for gitlab is down today...

Please check, my url is 
```
https://glcdn.githack.com/imgfo/example/-/raw/master/imgfo/example-api-1.17.1.json
```

![Screenshot from 2021-03-27 05-59-41](https://user-images.githubusercontent.com/9458941/112700897-c206f400-8ec1-11eb-9ea7-81509b851168.png)

**Comment by neoascetic** [comment]
Thanks for the report and sorry for inconvenience. It has been fixed.
