### ISSUE TITLE
how

### ISSUE THREAD

**Issue by snakemoddingiscoolandthisisalongname** [neoascetic/rawgithack#68]
how do i stop a link from working

**Comment by neoascetic** [comment]
Please explain what do you want

**Comment by snakemoddingiscoolandthisisalongname** [comment]
Thank you for responding I used rawgithack to make a link for a game and I would like to have that link not work anymore I was wondering if that was possible.

**Comment by neoascetic** [comment]
There is a "purge cache" button on the main page

**Comment by snakemoddingiscoolandthisisalongname** [comment]
Thank You
