### ISSUE TITLE
Access-Control-Allow-Origin missing?

### ISSUE THREAD

**Issue by HybridFox** [neoascetic/rawgithack#69]
I recently noticed resources failing to load on my website because of the `Access-Control-Allow-Origin` header missing.
Is this done with a reason because i am sure it was being send a while ago.

**Comment by neoascetic** [comment]
Hello. What files do you serve? I recently started to redirect "unknown" file extensions such as images and videos, etc, to GitHub itself.

**Comment by HybridFox** [comment]
Hey, i am loading in .HDR files: https://rawcdn.githack.com/pmndrs/drei-assets/aa3600359ba664d546d05821bcbca42013587df2/hdri/venice_sunset_1k.hdr

**Comment by neoascetic** [comment]
Some folks were abusing the service to serve copyrighted video files, so I tried to mitigate this issue. Will try to resolve it soon.

**Comment by HybridFox** [comment]
Thank you! I don't mind the redirect since the page it redirects to has correct Access-Control-Allow-Origin headers. But currently my browser just fails on being redirect at all since [the link](https://rawcdn.githack.com/pmndrs/drei-assets/aa3600359ba664d546d05821bcbca42013587df2/hdri/venice_sunset_1k.hdr) is missing the headers

**Comment by neoascetic** [comment]
I've added the header to the location link. Could you please quickly check if that works for you?

**Comment by HybridFox** [comment]
Hmmm, can't see it yet. Is it possible cloudflare still has it cached? I cleared the cache of my browser
<img width="772" alt="image" src="https://user-images.githubusercontent.com/7349146/154430001-999895d3-150c-4797-9f03-1988a1ed1cb5.png">

**Comment by neoascetic** [comment]
Well, it should redirect, at least from what I see it redirects

**Comment by neoascetic** [comment]
Let me know if you see something else working incorrectly, I will keep this open for a while

**Comment by HybridFox** [comment]
Well, it seems there is somewhere still some caching enabled. Firefox shows that the file is not redirect but has the correct headers:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/7349146/154431618-65ca2335-7a7b-4d65-b9a5-e9f6fad0a702.png">
cURL shows a redirect with the correct headers:
![image](https://user-images.githubusercontent.com/7349146/154431685-9a35c301-a8cd-4fc2-9400-25a5eb62bd9f.png)
and chrome shows a redirect without the headers:
![image](https://user-images.githubusercontent.com/7349146/154431730-596ac449-917a-4c5d-b027-8d0370a96236.png)

I would honestly trust the cURL the most. So it seems to be fixed  then
Let's indeed keep it open for a while to see if the situation resolves itself then :)

Thank you for the quick help!

**Comment by neoascetic** [comment]
Looks like it is fixed, closing
