### ISSUE TITLE
any way ? to purge cache faster ?

### ISSUE THREAD

**Issue by pamanbobb** [neoascetic/rawgithack#70]
Hei got bug on some code, but the file has been share on public. i has been remove the file on my repo but there still loaded.
i try to purge cache the rawcdn url for few time but the file but no change.

**Comment by neoascetic** [comment]
Hello. What is the url you want to purge?

**Comment by pamanbobb** [comment]
i just want to purge 3 file are now on public share.
this the raw url .
https://rawcdn.githack.com/pamanbobb/crypton/dc76860ad2e1cb2f55d3f98acfff56930730e0ea/lockhead.html
https://rawcdn.githack.com/pamanbobb/crypton/dc76860ad2e1cb2f55d3f98acfff56930730e0ea/universe.html
https://rawcdn.githack.com/pamanbobb/finished/bddad930aabf9ee04507b938036a06fd5fb6a215/sdk.js

Pada tanggal Kam, 10 Mar 2022 pukul 11.33 Pavel ***@***.***>
menulis:

> Hello. What is the url you want to purge?
>

**Comment by neoascetic** [comment]
They’re on publish share because they’re still in your repo. That’s how githack works — you can reference any commit you have in your repo. If you want these to disappear, you need to delete this commit from your repo and then purge the cache.

**Comment by pamanbobb** [comment]
i has been succesfull delete this commit from my repo and then purge the cache,
origin repo after delete. -> https://github.com/pamanbobb/crypton,

the raw url are send more purge cache.
https://rawcdn.githack.com/pamanbobb/crypton/dc76860ad2e1cb2f55d3f98acfff56930730e0ea/lockhead.html
https://rawcdn.githack.com/pamanbobb/crypton/dc76860ad2e1cb2f55d3f98acfff56930730e0ea/universe.html

but until now it still appears on public. what step do more.

**Comment by neoascetic** [comment]
That’s because the commit is still available on GitHub, it didn’t clean it (yet): https://github.com/pamanbobb/crypton/commit/dc76860ad2e1cb2f55d3f98acfff56930730e0ea

Unfortunately, I have no control over it. Perhaps recreation of the repo could help?
