### ISSUE TITLE
How to clear cache of CloudFlare's CDN ?

### ISSUE THREAD

**Issue by asfarmed** [neoascetic/rawgithack#72]
How to clear cache of CloudFlare's CDN ?
exemple:
https://rawcdn.githack.com/asfarmed/players/4107ea6e108f6dde6423427e6ff4b6c9e28badf3/yallashoot-live2.js

**Comment by neoascetic** [comment]
You can do that on this page: https://raw.githack.com/purge-cache

**Comment by asfarmed** [comment]
not work for me

https://rawcdn.githack.com/asfarmed/players/4107ea6e108f6dde6423427e6ff4b6c9e28badf3/yallashoot-live2.js
different from the original file
https://github.com/asfarmed/players/blob/main/yallashoot-live2.js

**Comment by neoascetic** [comment]
That’s correct, because the master branch has different hash. You’re referencing to the first commit in your first link.
