### ISSUE TITLE
Javascript file not loading on non-dev Chrome but loads fine on dev Chrome

### ISSUE THREAD

**Issue by kennethjmyers** [neoascetic/rawgithack#73]
I have [this project](https://github.com/kennethjmyers/SpellingBeeTrainer) and [this file](https://github.com/kennethjmyers/SpellingBeeTrainer/blob/main/public/popup.html) that I was using with raw.githack.com ([link to hosted version](https://raw.githack.com/kennethjmyers/SpellingBeeTrainer/main/public/trainer.html)).

On the development chrome browser it works fine, the [javascript file](https://github.com/kennethjmyers/SpellingBeeTrainer/blob/main/public/trainer.js) loads and everything works as I would expect. But when I try to open this on the non-dev/consumer browser, I get these errors:

```
GET https://raw.githack.com/kennethjmyers/SpellingBeeTrainer/main/public/trainer.js net::ERR_ABORTED 404

Refused to execute script from 'https://raw.githack.com/kennethjmyers/SpellingBeeTrainer/main/public/trainer.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
```

The file does seem to exist, you can [open it and see it](https://raw.githack.com/kennethjmyers/SpellingBeeTrainer/main/public/trainer.js), so I've tried to learn more about the second error and from what I read this seems to be determined on the server side and not by the [type I set here](https://github.com/kennethjmyers/SpellingBeeTrainer/blob/1634c1544a12e2f6428af4c7c031bc61a345a245/public/trainer.html#L296).

**Comment by neoascetic** [comment]
Hey, yeah, so MIME version is because of 404 returned from the server. Any specific Chrome version? It works on my side, I am able to load the file, so I can suspect this could be because of some antivirus program.
