### ISSUE TITLE
CI/CD implementation

### ISSUE THREAD

**Issue by mmcintosh** [neoascetic/rawgithack#76]
Hi,

Would it be possible to implement this as a solution via a ci/cd pipeline as a deploy function? It would be a great addition. Thx!

Mark

**Comment by neoascetic** [comment]
Hello.

Could you elaborate, please, what are use cases, how it is supposed to be used? Originally the service was made for quick URL replacements, because, if you want to do this via CI/CD, you can just deploy to GitHub Pages.
