### ISSUE TITLE
retrieval of .txt file

### ISSUE THREAD

**Issue by mpsuzuki** [neoascetic/rawgithack#77]
Thank you very much for keeping your excellent service! Please let me ask whether I'm using your service incorrectly, or I found a bug.

I'm making a JavaScript tool loading some JSON files (via Fetch API), like:

https://[gl.githack.com/mpsuzuki/mj-shrink-map/raw/dd777/index.html](https://gl.githack.com/mpsuzuki/mj-shrink-map/raw/dd77793067767262b4273d3394d9c9f6802ccaf8/index.html)
![image](https://github.com/neoascetic/rawgithack/assets/2202675/86a90793-6871-49ca-9c37-a72ed22d4669)

If I fetch JSON files, there is no problem.

But if I load a .TXT file, it fails, like this:

https://[gl.githack.com/mpsuzuki/mj-shrink-map/raw/0ee0b/index.html](https://gl.githack.com/mpsuzuki/mj-shrink-map/raw/0ee0b/index.html)
![image](https://github.com/neoascetic/rawgithack/assets/2202675/63f1e1a8-a9e7-4a34-8e83-b32aabf6f8ce)

Following errors were issued in console.
![image](https://github.com/neoascetic/rawgithack/assets/2202675/3a2892f3-ce7f-4424-8dc3-3087e540ee95)

What's wrong? Is there any difference between the handling of .JSON file and .TXT file?

**Comment by mpsuzuki** [comment]
I note: both of ivd-20220913.txt and ivd-20220913.json exist in the repository.

https://gitlab.com/mpsuzuki/mj-shrink-map/-/tree/0ee0b
![image](https://github.com/neoascetic/rawgithack/assets/2202675/15e5973a-b9d9-4a59-8fb0-46954dac43db)

**Comment by neoascetic** [comment]
Hey. That's because of CORS error. All non-supported file types are being redirected to the upstream and thus do not have permissive CORS headers.

**Comment by neoascetic** [comment]
I've added support for `.txt` files in [60b7854](https://github.com/neoascetic/rawgithack/commit/60b7854239684c50fac8c43b182b0ba444fc9207), please let me know if it works for you. I myself verified and it works now, just do not forget to clear your browser cache.

**Comment by mpsuzuki** [comment]
Thanks! I've confirmed that now .txt file is properly fetch-able.
Thank you very much for your prompt fix!!
