### ISSUE TITLE
how to clear dev URL cache (force refresh)?

### ISSUE THREAD

**Issue by trusktr** [neoascetic/rawgithack#79]
raw.githack.com mentions:

> New changes you push will be reflected within minutes.

But I've been waiting for 30 minutes so far, and it is not updating. For example this URL is outdated at time of writing:

https://rawcdn.githack.com/lume/three-projected-material/main/examples/index.html

This is the working version at the commit that was on `main` at time of writing:

https://rawcdn.githack.com/lume/three-projected-material/98575167c5a6c4765391543f8dcbd6409754082a/examples/index.html

I noticed however that this URL works:

https://raw.githack.com/lume/three-projected-material/main/examples/index.html

Is the `rawcdn` URL permanently broken or does it take longer to refresh?

**Comment by neoascetic** [comment]
Hello.

If you read the documentation carefully, you will see that rawcdn. should be used with caution, and you should only use hash and not branch names as the file will be cached permanently, based on the url, without any TTL specified.

On the other hand, for development only and fast updates you should use raw. domain — cache there has 5 minutes TTL.

So, everything works as expected. rawcdn is permanent CDN and caches everything forever (or at least tries to do so).

Hope this helps.

**Comment by neoascetic** [comment]
To purge cache, it is possible to use special form on the website, but this is available to our patrons only.

**Comment by trusktr** [comment]
Thanks! The form can be used for resetting a rawcdn cache when I, for example, make a new deployment to a branch?

Is `raw.` going to be slow again every 5 minutes? Or only if I push a new commit (for example when using a branch ref)?

**Comment by neoascetic** [comment]
Hello.

The service tries to be as fast as possible. It revalidates cache in the background, serving stale content until it is updated. But keep in mind that local cache is limited, so it may be already evicted even if it is still valid. 

Hope this helps.
