### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by phillipPhillip** [neoascetic/rawgithack#9]
https://cdn.rawgit.com/phillipphillip/the-hub/90e8223779f32ec258a4020f848f3eb18fe8e76e/torat-test.html

**Comment by neoascetic** [comment]
Here the right link: https://raw.githack.com/phillipPhillip/The-Hub/90e8223779f32ec258a4020f848f3eb18fe8e76e/Torat-Test.html

Filenames are case-sensitive.

**Comment by phillipPhillip** [comment]
thank you
